#!/usr/bin/env bash
:
#shellcheck disable=2034
{
  name="micropython"
  version="1.26.0"

  source="https://github.com/micropython/micropython/releases/download/v${version}/"
  archive_filename="${name}-${version}.tar.xz"
  src_path="${name}-${version}/"

  size="110526232"
  sha256="a1b8e0f6bf7a8a78b55ac865c46c4c45f9623a86a1785d2063ff1cb3b6e661d7"

  license="MIT"
  license_file="LICENSE"

  conflicts=""
  depends=""
  optional=""
}

p_prepare() {
  # FIXME: building stuff in p_prepare is not cool - fix patches so that they
  # don't break the host build...
  #
  # Build mpy-cross for host if not already built
  #
  if [ ! -f "${PREFIX_PORT_WORKDIR}/mpy-cross/build/mpy-cross" ]; then
    CFLAGS="" LDFLAGS="" make -C "${PREFIX_PORT_WORKDIR}/mpy-cross" all
  fi

  b_port_apply_patches "${PREFIX_PORT_WORKDIR}"
  cp -va "${PREFIX_PORT}/001_mpconfigport.mk" "${PREFIX_PORT_WORKDIR}/ports/unix/mpconfigport.mk"
}

p_build() {
  #
  # Micropython internal use stack/heap size (not actual application stack/heap)
  # Values are to be overwritten in _targets/build.project.*
  #
  : "${UPYTH_STACKSZ=4096}"
  : "${UPYTH_HEAPSZ=16384}"

  # Some micropython tests needs more memory
  if [ "$LONG_TEST" = "y" ]; then
    UPYTH_STACKSZ=16384
    UPYTH_HEAPSZ=80000
  fi

  #
  # Architecture specific flags/values set
  #

  # TODO: use strip manually
  if [ "${TARGET_FAMILY}" = "armv7m7" ]; then
    STRIPEXP="--strip-unneeded"
  elif [ "${TARGET_FAMILY}" = "ia32" ]; then
    STRIPEXP="--strip-all"
  else
    b_log "Warning! Phoenix-RTOS for ${TARGET_FAMILY} does not support MicroPython compilation (yet!)"
    b_log "The compilation attempt will start in 5 seconds..."
    sleep 5
  fi
  export STRIPFLAGS_EXTRA="${STRIPEXP}"
  export PHOENIX_MATH_ABSENT="expm1 log1p asinh acosh atanh erf tgamma lgamma copysign __sin __cos __tan __signbit"
  export LDFLAGS_EXTRA="${CFLAGS} ${LDFLAGS}"
  export CFLAGS_EXTRA="${CFLAGS} -DUPYTH_STACKSZ=${UPYTH_STACKSZ} -DUPYTH_HEAPSZ=${UPYTH_HEAPSZ} "
  # clear original ld-format ldflags/cflags
  export LDFLAGS=""
  export CFLAGS=""

  #
  # Build and install micropython binary
  #
  make -C "${PREFIX_PORT_WORKDIR}/ports/unix" all CROSS_COMPILE="${CROSS}"

  cp -a "${PREFIX_PORT_WORKDIR}/ports/unix/build-standard/micropython" "$PREFIX_PROG_STRIPPED"
  b_install "$PREFIX_PROG_TO_INSTALL/micropython" /bin/
}

p_build_test() {
  PREFIX_UPYTH_TESTS_SRC="${PREFIX_PORT_WORKDIR}/tests"
  PREFIX_UPYTH_TESTS_DES="${PREFIX_ROOTFS}/usr/test/micropython"

  # Directories in micropython test/ directory from which tests are sourced
  UPYTH_TESTS_DIRS="basics micropython float import io misc unicode extmod ports/unix cmdline"

  echo "Copying micropython tests and generating expected results"

  mkdir -p "$PREFIX_UPYTH_TESTS_DES"

  # Copying expected outputs for tests, which differs from these generated by CPython
  cp -r "$PREFIX_PORT/exp_prefabs/." "$PREFIX_UPYTH_TESTS_DES"

  CPYTHON3="${MICROPY_CPYTHON3:-python3}"
  CPYTHON3_CMD="$CPYTHON3 -BS"

  for dir in $UPYTH_TESTS_DIRS; do
    cp -r "$PREFIX_UPYTH_TESTS_SRC/$dir" "$PREFIX_UPYTH_TESTS_DES"
    # Creating expected outputs for tests manually, as micropython resigned from this functionality
    des_dir=$(basename "$dir")
    for test in "$PREFIX_UPYTH_TESTS_DES"/"$des_dir"/*.py; do
      if [ -f "$test.exp" ]; then
        continue
      fi

      cd "$PREFIX_UPYTH_TESTS_DES/$des_dir" && $CPYTHON3_CMD "$(basename "$test")" >"$test.exp" 2>&1 || true
      sed -i 's/\r\n/\n/g' "$test.exp"
    done
  done
}
