--- fs_mark-3.3/Makefile	2023-07-10 15:47:05.889696230 +0200
+++ fs_mark-3.3.phoenix/Makefile	2023-11-21 18:37:52.606955908 +0100
@@ -6,29 +6,24 @@
 # Modifications include using fsync after wrting to flush to disk and changes to check return
 # values from syscalls.
 #
-DIR1= /test/dir1
-DIR2= /test/dir2
 
-COBJS= fs_mark.o lib_timing.o
+include $(PREFIX_PROJECT)/phoenix-rtos-build/Makefile.common
 
-CC ?= gcc
-CFLAGS ?= -O2
-LDFLAGS ?=
-CFLAGS += -Wall -D_FILE_OFFSET_BITS=64
+.DEFAULT_GOAL := all
 
-all: fs_mark 
+# default path for the programs to be installed in rootfs
+DEFAULT_INSTALL_PATH := /bin
 
-fs_mark.o: fs_mark.c fs_mark.h
+NAME := fs_mark
+LOCAL_SRCS := fs_mark.c lib_timing.c
+LOCAL_LDFLAGS += -z stack-size=22288
 
-fs_mark: fs_mark.o lib_timing.o
-	$(CC) $(CFLAGS) -o fs_mark fs_mark.o lib_timing.o $(LDFLAGS)
+include $(binary.mk)
 
-test: fs_mark
-	./fs_mark -d ${DIR1} -d ${DIR2} -s 51200 -n 4096
-	./fs_mark -d ${DIR1} -d ${DIR2} -s 51200 -n 4096 -r 
-	./fs_mark -d ${DIR1} -d ${DIR2} -s 51200 -n 4096 -D 128
-	./fs_mark -d ${DIR1} -d ${DIR2} -s 51200 -n 4096 -r -D 128
-
-clean:
-	rm -f ${COBJS} fs_mark fs_log.txt
+# create generic targets
+DEFAULT_COMPONENTS := $(ALL_COMPONENTS)
 
+.PHONY: all install clean
+all: $(DEFAULT_COMPONENTS)
+install: $(patsubst %,%-install,$(DEFAULT_COMPONENTS))
+clean: $(patsubst %,%-clean,$(ALL_COMPONENTS))
