# vim:sw=2:ts=2
# static linters which can be run in a single repo (do not need phoenix-rtos-project)
name: lint

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  call-lint:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/lint.yml@master
